"""legacy-cu -- a stand-in for a credit-union back-office servicing console.

This app exists to be automated against, and it is deliberately unpleasant to
automate. Real back-office banking software is server-rendered, frame-based,
laid out in nested tables, and carries no test ids; element ids are generated by
the framework and change on every render. Building the target ourselves is the
only way to reproduce that faithfully *and* to inject the runtime conditions the
system is supposed to survive -- a record that does not exist, a permission
denial, a session that times out mid-flow.

Specifically hostile, on purpose:

* ``<frameset>`` with a nav frame and a content frame, so automation has to
  traverse frames rather than assuming one document.
* Table-based layout with ``<font>`` tags and inline styles.
* Element ids regenerated per render (``ctl00_wpz_ctl03_txt7``), which defeats
  any strategy that records a selector.
* No ``<label for>``. Fields are labelled by the table cell to their left, which
  is how these applications actually look, and which forces a targeting strategy
  to understand proximity rather than markup.
* Nothing resembling a test id anywhere.

None of the data here is real, and none of it resembles a real person.
"""
