"""Typed contracts for capabilities, results, and tenant overlays.

Everything the rest of the system passes around is defined here. The schema is
deliberately the first thing to read: it encodes most of the
design decisions in a form that is checked at runtime rather than described in
a comment.
"""

from cua.schema.capability import (
    Action,
    Anchor,
    AnchorKind,
    BBox,
    BusinessOutcome,
    Capability,
    Checkpoint,
    ClickAction,
    ElementDescriptor,
    ExtractAction,
    FallbackHint,
    FallbackKind,
    NavigateAction,
    OutputSpec,
    ParamSpec,
    ParamType,
    Predicate,
    PredicateKind,
    PressKeyAction,
    Provenance,
    RecoveryPolicy,
    RecoveryStrategy,
    RiskClass,
    RiskProfile,
    SelectOptionAction,
    Step,
    SurfaceBinding,
    SurfaceKind,
    TypeTextAction,
    ValueRef,
    WaitForAction,
    WaitSpec,
)
from cua.schema.results import (
    DiscoveryResult,
    EscalationTrace,
    FailureCategory,
    FailureReport,
    OutcomeReport,
    RecoveryTrace,
    ReplayResult,
    ReplayStatus,
    StepStatus,
    StepTrace,
)

__all__ = [
    "Action",
    "Anchor",
    "AnchorKind",
    "BBox",
    "BusinessOutcome",
    "Capability",
    "Checkpoint",
    "ClickAction",
    "DiscoveryResult",
    "ElementDescriptor",
    "EscalationTrace",
    "ExtractAction",
    "FailureCategory",
    "FailureReport",
    "FallbackHint",
    "FallbackKind",
    "NavigateAction",
    "OutcomeReport",
    "OutputSpec",
    "ParamSpec",
    "ParamType",
    "Predicate",
    "PredicateKind",
    "PressKeyAction",
    "Provenance",
    "RecoveryPolicy",
    "RecoveryStrategy",
    "RecoveryTrace",
    "ReplayResult",
    "ReplayStatus",
    "RiskClass",
    "RiskProfile",
    "SelectOptionAction",
    "Step",
    "StepStatus",
    "StepTrace",
    "SurfaceBinding",
    "SurfaceKind",
    "TypeTextAction",
    "ValueRef",
    "WaitForAction",
    "WaitSpec",
]
